Feature/fetch data
pasharuban/NeoflexTasksProject pull request #5
Opened 2021-12-21 14:40 UTC by pasharuban

:)

2021-12-27 08:22 UTC, Kantrop requested changes

2021-12-27 08:22 UTC, Kantrop commented on src/constants/types.ts
> +export const REGISTRATION_SUCCESS = 'REGISTRATION _SUCCESS';
лучше назвать файл actionTypes

2021-12-27 08:22 UTC, Kantrop commented on src/pages/TasksTablePage/components/IncomingClaim/FormButtons.tsx
> +          const updatedClaim = {
лучше не прописывать логику внутри верстки. Если требуется доп махинации с данными, обьявление переменных и прочее, то надо обьявлять функцию выше. либо скормить обьект напрямую,

2021-12-27 08:22 UTC, Kantrop commented on src/pages/TasksTablePage/components/IncomingClaim/FormButtons.tsx
> +          const updatedClaim = {
и тут.
Вообще передачу пропсов надо держать максимально сухой. В идеале передавать одну переменную.
Эти два обработчика на 99% одинаковые. можно вынести в одну функцию, которая будет принимать в себя status

2021-12-27 08:22 UTC, Kantrop commented on src/pages/TasksTablePage/components/IncomingClaim/IncomingClaimForm.tsx
> +  if ((loading || currentClaim.noData) && !error) {
выше деструктуризация, а тут нет. поч?
кстати, если currentClaim нет, то мб undefined в сторе хранить? тогда можно проверять наличие вцелом, а не полагать на флаг

2021-12-27 08:22 UTC, Kantrop commented on src/pages/TasksTablePage/components/NewClaim/NewClaimForm.tsx
>      handleRedirectToDashboard(history);
лучше обернуть await в try/catch, либо обернуть handleRedirectToDashboard в then. т.к. редирект произойдет даже при провалившемся запросе.

2021-12-27 08:22 UTC, Kantrop commented on src/pages/TasksTablePage/components/TasksTable.tsx
> +      emptyText: (
locale здесь используется немного не по назначению, но молодец что раскопал. 
у таблицы есть проп loading как раз на случай асинхронности. настраивается как компонент спинера https://ant.design/components/spin/#API

2021-12-27 08:22 UTC, Kantrop commented on src/pages/TasksTablePage/components/TasksTable.tsx
> +      emptyText: <h2 style={{ color: 'red', fontFamily: 'Inter' }}>{errorMessage}</h2>,
думаю h2 тут немного лишнее. Давай чуть-чуть успокоим и сделаем простой span

2021-12-27 08:22 UTC, Kantrop commented on src/redux/actions/actionRegisterUser.ts
>            if (res.data.message) dispatch(actionAuthFailure(res.data.message));
сразу не увидел. если у ифа есть else не рекомендуется использовать однострочное написание

2021-12-27 08:22 UTC, Kantrop commented on src/redux/reducers/postDataReducer.ts
> +const postDataReducer = (state = initialState, action: ActionTypeTypes): initialStateType => {
не следует использовать название метода, каким получаются данные в редьюсере. т.к. редьюсеру все равно откуда данные.
Да и в экшене привязка не рекомендуема, но допустима (с оговорками)

2021-12-27 08:22 UTC, Kantrop commented on src/redux/reducers/postDataReducer.ts
> +    case POST_DATA_FAILURE:
из-за наименования здесь складывается ощущение, что речь про данные поста, а не данные полученые постом. Привязываться к методу получения данных не оч хорошо, но допустимо, если это важно в бизнес логике. (в таком случае обычно пишут BY_POST) Ведь если потом данные станут приходить гетом - семантика нарушится.

2021-12-29 21:01 UTC, pasharuban commented on src/pages/TasksTablePage/components/IncomingClaim/IncomingClaimForm.tsx
> +  if ((loading || currentClaim.noData) && !error) {
По поводу флага noData,решил его оставить,потому что с undefined заморочек много.
Например, при деструктуризации будет ругать,что поля возможно undefined и тд => прийдется править

2022-01-19 15:22 UTC, merged